<template>
    <div class="w-full h-screen px-32 pt-12 overflow-y-auto no-scrollbar">
        <div class= "w-10/12 p-8 text-font flex justify-between mx-auto">
            <div class="header pb-4">
                <span class="text-5xl font-title text-main">Search from content</span>
            </div>
                <div class="w-1/2">
                <label class="search-label w-full">
                    <input type="text" class="w-full h-12 p-1 pl-4 border-2 rounded-2xl text-font bg-panel text-lg" placeholder="content word" v-model="state.word" @keyup.enter="search">
                </label>
            </div>
        </div>
        <div v-if="state.loadSpin" class="w-full h-64 text-font text-4xl mt-10 align-middle text-center">
            <div class="flex justify-center">
                <svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" width="200px" height="200px" viewBox="0 0 100 100" preserveAspectRatio="xMidYMid" style="margin-right:-2px;display:block;background-repeat-y:initial;background-repeat-x:initial;background-color:rgba(255, 255, 255, 0);animation-play-state:paused" 
                class="animate-spin">
                    <g transform="rotate(0 50 50)" style="transform:matrix(1, 0, 0, 1, 0, 0);animation-play-state:paused" ><rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#b7b7b7" opacity="0.0833334" style="opacity:0.0833334;animation-play-state:paused" ></rect></g>
                    <g transform="rotate(30 50 50)" style="transform:matrix(0.866025, 0.5, -0.5, 0.866025, 31.6987, -18.3013);animation-play-state:paused" ><rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#b7b7b7" opacity="0.166667" style="opacity:0.166667;animation-play-state:paused" ></rect></g>
                    <g transform="rotate(60 50 50)" style="transform:matrix(0.5, 0.866025, -0.866025, 0.5, 68.3013, -18.3013);animation-play-state:paused" ><rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#b7b7b7" opacity="0.25" style="opacity:0.25;animation-play-state:paused" ></rect></g>
                    <g transform="rotate(90 50 50)" style="transform:matrix(6.12323e-17, 1, -1, 6.12323e-17, 100, 0);animation-play-state:paused" ><rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#b7b7b7" opacity="0.333333" style="opacity:0.333333;animation-play-state:paused" ></rect></g>
                    <g transform="rotate(120 50 50)" style="transform:matrix(-0.5, 0.866025, -0.866025, -0.5, 118.301, 31.6987);animation-play-state:paused" ><rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#b7b7b7" opacity="0.416667" style="opacity:0.416667;animation-play-state:paused" ></rect></g>
                    <g transform="rotate(150 50 50)" style="transform:matrix(-0.866025, 0.5, -0.5, -0.866025, 118.301, 68.3013);animation-play-state:paused" ><rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#b7b7b7" opacity="0.5" style="opacity:0.5;animation-play-state:paused" ></rect></g>
                    <g transform="rotate(180 50 50)" style="transform:matrix(-1, 1.22465e-16, -1.22465e-16, -1, 100, 100);animation-play-state:paused" ><rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#b7b7b7" opacity="0.583334" style="opacity:0.583334;animation-play-state:paused" ></rect></g>
                    <g transform="rotate(210 50 50)" style="transform:matrix(-0.866025, -0.5, 0.5, -0.866025, 68.3013, 118.301);animation-play-state:paused" ><rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#b7b7b7" opacity="0.666667" style="opacity:0.666667;animation-play-state:paused" ></rect></g>
                    <g transform="rotate(240 50 50)" style="transform:matrix(-0.5, -0.866025, 0.866025, -0.5, 31.6987, 118.301);animation-play-state:paused" ><rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#b7b7b7" opacity="0.75" style="opacity:0.75;animation-play-state:paused" ></rect></g>
                    <g transform="rotate(270 50 50)" style="transform:matrix(-1.83697e-16, -1, 1, -1.83697e-16, 7.10543e-15, 100);animation-play-state:paused" ><rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#b7b7b7" opacity="0.833333" style="opacity:0.833333;animation-play-state:paused" ></rect></g>
                    <g transform="rotate(300 50 50)" style="transform:matrix(0.5, -0.866025, 0.866025, 0.5, -18.3013, 68.3013);animation-play-state:paused" ><rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#b7b7b7" opacity="0.916667" style="opacity:0.916667;animation-play-state:paused" ></rect></g>
                    <g transform="rotate(330 50 50)" style="transform:matrix(0.866025, -0.5, 0.5, 0.866025, -18.3013, 31.6987);animation-play-state:paused" ><rect x="47" y="24" rx="3" ry="6" width="6" height="12" fill="#b7b7b7" opacity="1" style="animation-play-state:paused" ></rect></g><!-- generated by https://loading.io/ -->
                </svg>
            </div>
            <div>
                Searching...
            </div>
        </div>
        <perfect-scrollbar v-else-if="state.notices.length != 0" class="no-scrollbar w-10/12 h-3/4 p-4 mx-auto">
            <div v-for="notice in state.notices" :key="notice.postId" @click.stop="searchOne(notice.postId)" class="text-font bg-panel h-1/5 overflow-y-hidden rounded-xl shadow-lg p-4 m-2 my-4">
                <div class = "flex justify-between p-3 pb-2">
                    <div class="font-bold w-2/3 overflow-hidden text-bold text-xl">
                        {{notice.team}} / {{notice.channel}}
                    </div>
                    <div class="w-1/6 overflow-hidden text-lg text-right text-gray-600">
                        {{notice.startTime}}
                    </div>
                    <div class="w-1/6 overflow-hidden text-lg text-right mr-10 text-gray-600">
                        {{notice.user}}
                    </div>
                </div>
                <div class="w-full overflow-hidden p-3 pt-0 text-lg whitespace-normal truncate m-0 text-gray-500">
                    {{notice.content}}
                </div>
            </div>
        </perfect-scrollbar>
        <div v-else class="w-full h-64 text-font text-4xl align-middle text-center mt-10">
            No search results.
        </div>
        <div v-if="state.open" class="z-50 absolute top-1/2 left-1/2 w-4/5 h-1/2 transform -translate-x-1/2 -translate-y-1/2">
            <search-content :notice="state.noticeDetail" @close="state.open = false"/>
        </div>
    </div>
</template>
<script>
import { reactive } from 'vue'
import { useStore } from 'vuex'
import { useRouter } from 'vue-router'
import SearchContent from '@/components/notice/SearchContent.vue'
import { getTime, getTitleLen } from '../../common/lib/function.js';

export default {
    name: 'DetailPage',
    components: {
        SearchContent
    },

    setup(){
        const store = useStore()
        const router = useRouter()
        const state = reactive({
            word : "",
            token : store.getters['root/getToken'],
            notices: [],
            noticeDetail:{
                },
            open: false,
            loadSpin: false,
        })

        const search = () =>{
            state.loadSpin = true
            let payload = {
                "word" : state.word,
                "token": state.token,
            }
            store.dispatch('root/getNoticeSearch', payload)
            .then((result) => {
                state.notices = []
                result.data.notifications.forEach(node => {
                    let notice = {
                        team : node.channel.team.name,
                        channel: node.channel.name,
                        content: getTitleLen(node.content, 150),
                        files: node.files,
                        user: node.user.userName,
                        startTime: getTime(node.startTime),
                        endTime: getTime(node.endTime),
                        postId: node.token,
                        time: getTime(node.time)
                    }
                    state.notices.push(notice)
                });
                setTimeout(function() { state.loadSpin = false }, 500);
            })
            .catch((err)=>{
                setTimeout(function() { state.loadSpin = false }, 500);
                console.log(err)
            })
        }

        const searchOne = (postId) =>{
            state.open = true
            let payload = {
                "postId" :postId,
                "token": state.token,
            }
            store.dispatch('root/getNoticeDetail', payload)
            .then((result) => {
                let notice = {
                    team: result.data.channel.team.name,
                    channel: result.data.channel.name,
                    content: result.data.content,
                    files: result.data.files,
                    user: result.data.user.userName,
                    userId: result.data.user.userId,
                    startTime: getTime(result.data.startTime),
                    endTime: getTime(result.data.endTime),
                    postId: result.data.token,
                    time: getTime(result.data.time)
                }
                state.noticeDetail = notice;
            })
            .catch((err)=>{
                console.log(err)
            })
        }

        const init = ()=>{
        }


        init()
        return { state, search, searchOne }
    }
};
</script>

<style scoped>
label {
    position: relative;
}

label:before {
    content: "";
    position: absolute;
    left: 20px;
    top: 0;
    bottom: 0;
    width: 20px;
    background: url("data:image/svg+xml,%3Csvg xmlns='http://www.w3.org/2000/svg' width='25' height='25' viewBox='0 0 25 25' fill-rule='evenodd'%3E%3Cpath d='M16.036 18.455l2.404-2.405 5.586 5.587-2.404 2.404zM8.5 2C12.1 2 15 4.9 15 8.5S12.1 15 8.5 15 2 12.1 2 8.5 4.9 2 8.5 2zm0-2C3.8 0 0 3.8 0 8.5S3.8 17 8.5 17 17 13.2 17 8.5 13.2 0 8.5 0zM15 16a1 1 0 1 1 2 0 1 1 0 1 1-2 0'%3E%3C/path%3E%3C/svg%3E") center / contain no-repeat;
}

input {
    padding: 10px 50px;
}
</style>